### PR TITLE
Use config/security-bindings.yaml as default file

### PR DESCRIPTION
**Pull request by ruhan1**
Use config/security-bindings.yaml as default file.

### CODE REVIEW

**Comment by ruhan1** [comment]
sonatype reports err but it does not make sense. not know how to get rid of it.

**Review by ligangty — COMMENTED** [review]
@ruhan1 Sorry for late reply. But I'm a little confused why we need this change, as the classpath one as default is enough to provide default role-bindings. If the config/ one is needed, just marked it in application.yaml is ok.

**Comment by ruhan1** [comment]
With this pr, we can ignore the config in application.yaml
I see our services all have their own security files in default config/ dir. And they have same config line in application.yaml . This seems a bit redundant.

**Comment by ligangty** [comment]
> With this pr, we can ignore the config in application.yaml I see our services all have their own security files in default config/ dir. And they have same config line in application.yaml . This seems a bit redundant.

Ok and LGTM.

**Pull request merged**
